 name: Deploy 

 on: [push]

 jobs:
   build:

     runs-on: ubuntu-latest

     steps:
     - name: Checkout
       uses: actions/checkout@v2
       with:
         ref: master # 源文件的分支

     - name: Setup Node
       uses: actions/setup-node@v1
       with:
         node-version: "18.16"

     - name: Setup Hexo
       env:
         ACTION_DEPLOY_KEY: ${{ secrets.HEXO_DEPLOY_KEY }} # secret.后面填你4.2步写的key的名字
       run: |
         mkdir -p ~/.ssh/
         echo "$ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
         chmod 700 ~/.ssh
         chmod 600 ~/.ssh/id_rsa
         ssh-keyscan github.com >> ~/.ssh/known_hosts
         git config --global user.email "STI_LZ@outlook.com"
         git config --global user.name "STI-LZ"
         npm install hexo-cli -g
         npm install

     - name: Deploy
       run: |
         hexo clean
         hexo deploy